### PR TITLE
Clarify `argument can not have class as its default value` error

### LINKED ISSUE #131: Improve _class named arguments default value error message.
See #127 #128

### PR DESCRIPTION
**Pull request by thedrow**
Fixes #131.

### CODE REVIEW

**Comment by proofit404** [comment]
Yes, It's okay but we [format code a little bit different](https://github.com/dry-python/stories/blob/b8bf3995c84cc4f2b56e6b407b8190bf4263faf5/src/stories/_contract.py#L569-L577) usually.

Thanks for your contribution.

Best regards, 
Artem.

**Comment by thedrow** [comment]
So I should extract the message into a constant?

**Comment by proofit404** [comment]
Yes, please.

**Comment by thedrow** [comment]
Go ahead and merge this :)

**Comment by proofit404** [comment]
Thanks!

**Pull request merged**
