### PR TITLE
Reword DependencyError Message

### PR DESCRIPTION
**Pull request by KevinBoyette**

### CODE REVIEW

**Comment by proofit404** [comment]
Hi, thanks for your contribution!

Could you fix the CI build so I could merge it?

Best regards,
Artem.

**Comment by KevinBoyette** [comment]
@proofit404 of course!

**Comment by proofit404** [comment]
Thanks!
:tada: :cake: :tada:

**Comment by proofit404** [comment]
BTW https://twitter.com/dry_py/status/1174625965206659072

**Comment by KevinBoyette** [comment]
Thank you!

**Pull request merged**
