### PR TITLE
Use a dict comprehension

### PR DESCRIPTION
**Pull request by thedrow**
This is mostly a style fix but it is slightly faster to build a dictionary this way as well.

### CODE REVIEW

**Comment by proofit404** [comment]
Thanks for your contribution!

I didn't know Python2 supports dictionary comprehensions.

I'll merge it for sure after I fix the build.

Regards,
Artem.

**Comment by thedrow** [comment]
Python 2.7 does. Python 2.6 doesn't as far as I recall.

**Comment by proofit404** [comment]
We all green! :tada: 

Please, rebase.

**Comment by thedrow** [comment]
Done!
The tests pass as expected.

**Comment by thedrow** [comment]
I'm not sure why it's stuck.
Can you restart the build?

**Comment by thedrow** [comment]
No idea what's going on here.
Can we merge this anyway?

**Pull request merged**
